### ISSUE TITLE
materials.py not working on Blender 4.x

### ISSUE THREAD

**Issue by rudzik8** [random-geek/meshport#12]
![image](https://github.com/random-geek/meshport/assets/87843378/97d4c476-a942-4012-87bf-17390a286c73)

`KeyError: "bpy_prop_collection[key]: key "Specular" not found"`

Apparently, they renamed it in 4.0. After a bit of googling I found [this solution](https://github.com/ross-g/io_pdx_mesh/pull/87/commits/aae9baa55e95fe9a8c232fe2a5dfd3b69d078992) for IO PDX MESH, which turned out to be applicable here as well.

As a quick-fix, on line 50: `prin.inputs["Specular IOR Level"].default_value = 0`

After applying it, the script worked fine.

**Comment by ChaoticByte** [comment]
@rudzik8 I took that opportunity by forking the mod and creating a PR. Thanks for the fix ^^

**Comment by random-geek** [comment]
Oops, never saw this issue. Fixed by b6dc83be19173950c454fff5a58eef28c7c72231.
