### ISSUE TITLE
add `mat.blend_method="CLIP"` to enable transparency on blender 2.91.0

### ISSUE THREAD

**Issue by S-G-iscoding** [random-geek/meshport#6]
With Blender 2.91.0, the script does not enable transparency.

If `mat.blend_method="CLIP"` is added to the script (before the ` #Deselect all`-line), it is working and glass or leaves become transparent parts.

I haven't created a pull request because it is only about one single line of code.

**Comment by random-geek** [comment]
Hm, I tried this in the latest version of Blender (2.93.0) with Cycles, and transparency seems to work fine. Is this an issue with Eevee or something? Or has the issue been resolved since 2.91.0?

**Comment by random-geek** [comment]
Fixed.

67d08f7
