### ISSUE TITLE
stick to select area (like worldedit)

### ISSUE THREAD

**Issue by AFCMS** [random-geek/meshport#7]

**Comment by wsor4035** [comment]
alternatively optionally use worldedits two markers by default if installed and map mesh1 and mesh2 to //1 and //2

**Comment by random-geek** [comment]
Done; I added selection marker entities and an area selector wand that works just like WorldEdit's.

I don't currently have much interest in integrating with WorldEdit, but thanks for the suggestion. :)

**Comment by AFCMS** [comment]
thanks!
