### ISSUE TITLE
materials.py conversion script for Blender 3.0

### ISSUE THREAD

**Issue by sbrl** [random-geek/meshport#9]
I found the included `materials.py` script doesn't work very well in Blender 3.0 - it makes all materials very light in colour and difficult to see.

To fix this problem, @VorTechnix and I wrote a new script:

```python
import bpy

context = bpy.context

for o in context.selected_objects:
    for m in o.material_slots:
        print(m.material.name)
        m.material.blend_method = 'HASHED'
        
        node_tree = m.material.node_tree
        
        if node_tree.nodes.find('Image Texture') > -1:
            node_tree.nodes['Image Texture'].interpolation = "Closest"
            node_tree.links.new(
                node_tree.nodes['Image Texture'].outputs['Alpha'],
                node_tree.nodes['Principled BSDF'].inputs['Alpha']
            )
﻿
```

I don't think it does everything the old one did, but it works well enough at least.

Posting here just in case it's useful for others.

**Comment by random-geek** [comment]
A couple new inputs got added to the Principled shader, so now the old script links texture alpha to emission. 🤦‍♂️ 

Addressing sockets by their string names is a good idea, as well as only modifying selected objects. I'll take a look at this script and maybe integrate some of those ideas into materials.py.

**Comment by random-geek** [comment]
Should be fixed now; thanks for the suggestions!

**Comment by sbrl** [comment]
Awesome, thanks! I'll give it a try.

**Comment by random-geek** [comment]
Changes have been released, closing.
